import './globals.css'
import Layout from "@/components/Layout";


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    <html lang="fr">
      <body>
            <Layout>
                {children}
            </Layout>
      </body>
    </html>
  )
}
