export const Program = {
    items : [
        {
            id: 1,
            title: "12h30 - 12h50 : Les moyens de transports du futur",
            text : "Conférence cool",
            image_path : "/images/green_shift_logo.png",
            color: "blue-400",
            group: [
                "Raphael CHEVALIER",
                "Titouan LAMBRECQ",
                "Bastien AELTERS",
                "Hugo BERTRAND",
            ],
        },
        {
            id: 2,
            title: "??h?? - Les robots autonomes au sein des villes durables",
            text : "Conférence cool",
            image_path : "/images/green_shift_logo.png",
            color: "red-400",
            group: [
                "Quentin LE FORTIER",
                "Léo GILLES",
                "Antoine SOULAIRE",
                "Dorian BUQUET",
            ],
        },
        {
            id: 3,
            title: "??h?? - Des robots pour améliorer les villes",
            text : "Conférence cool",
            image_path : "/images/green_shift_logo.png",
            color: "yellow-400",
            group: [
                "Cédric LETALLEUR",
                "Théo LANGLOIS",
                "Ophélien FOUQUES",
            ],
        },
        {
            id: 4,
            title: "??h?? - Le futur des transports en commun",
            text : "Conférence cool",
            image_path : "/images/green_shift_logo.png",
            color: "violet-400",
            group: [
                "Valentin PAIN",
                "Nathan PORET",
                "Benjamin BRIFAULT",
                "Etienne CANDAT",
            ],
        },
        {
            id: 5,
            title: "??h?? - Mise en place de solutions pour une ville durable : les risques et obstacles",
            text : "Conférence cool",
            image_path : "/images/green_shift_logo.png",
            color: "green-400",
            group: [
                "Gaetan ALORY",
                "Baptiste LUBRANO LAVADERA",
                "Anaël HAUZAY",
                "Alexi AL KHOURY",
            ],
        },
        {
            id: 6,
            title: "??h?? - La gestion de la pollution dans les zones densément habitées et utilisées",
            text : "Conférence cool",
            image_path : "/images/green_shift_logo.png",
            color: "blue-400",
            group: [
                "Arthur LECRAS",
                "Pierre GARRIDO",
            ],
        },
        {
            id: 7,
            title: "??h?? - La mobilité intelligente : adéquation des besoins croissants et des ressources limitées",
            text : "Conférence cool",
            image_path : "/images/green_shift_logo.png",
            color: "red-400",
            group: [
                "Antoine TREFEU",
                "Aurélien LE LEVIER",
                "Tristan PASQUET",
            ],
        },
        {
            id: 8,
            title: "??h?? - Chantiers et bâtiments du futur : l'éco-conception",
            text : "Conférence cool",
            image_path : "/images/green_shift_logo.png",
            color: "yellow-400",
            group: [
                "Lucas AGNES",
                "Gauthier CLET",
                "Valentin PERRIER",
                "Maxence PIGNE",
            ],
        },
        {
            id: 9,
            title: "??h?? - L'application de la gamification sur l'écologie",
            text : "Conférence cool",
            image_path : "/images/green_shift_logo.png",
            color: "violet-400",
            group: [
                "Enzo LEVASSEUR",
                "Adrien MOUTON",
            ],
        },
        {
            id: 10,
            title: "??h?? - Les impacts environnementaux de l'industrie 4.0",
            text : "Conférence cool",
            image_path : "/images/green_shift_logo.png",
            color: "green-400",
            group: [
                "Achille BROSSIER",
                "Dove-Steve BINGO KPOGNON",
            ],
        },
    ]
}
